// This file was autogenerated by ../js/closure-library/closure/bin/build/depswriter.py.
// Please do not edit.
goog.addDependency('app/index.js', ['app.index'], ['goog.dom', 'goog.events', 'goog.events.EventType']);
goog.addDependency('app/uistudy.js', ['app.uistudy'], ['goog.dom', 'goog.events', 'goog.events.EventType', 'goog.ui.Button']);
